### ISSUE TITLE
MP3 Decoder

### ISSUE THREAD

**Issue by AntonDrubetskiy** [cpuimage/tinymp3#1]
Hey! Thanks for a great example of an MP3 encoder!

The file main.c implements an example of an MP3 encoder.
Tell me where to find an example of an MP3 decoder in this project?

**Comment by cpuimage** [comment]
> Hey! Thanks for a great example of an MP3 encoder!
> 
> The file main.c implements an example of an MP3 encoder. Tell me where to find an example of an MP3 decoder in this project?

https://github.com/mackron/dr_libs 
or
https://github.com/lieff/minimp3

**Comment by AntonDrubetskiy** [comment]
Thank you very much!
